### ISSUE TITLE
Nginx PostgreSQL

### ISSUE THREAD

**Issue by sammcj** [guarinogabriel/Mac-CLI#12]
It would be great if there was integration with Nginx and PostgreSQL rather than the old LAMP style webstack that isn't so common in modern web development anymore.

**Comment by guarinogabriel** [comment]
Hi @sammcj,

Thanks for your suggestion. We are working on modularity for the project, that means that the CLI will be configurable through plugins: https://github.com/guarinogabriel/mac-cli/issues/3

I will let you know when modularity is finished, since that will let us add a plugin for each of the webstacks and you will be able to configure your mac webstack on the CLI by including the Nginx/PostgreSQL plugin.

**Comment by sammcj** [comment]
Great!

Thank you so much.

**Comment by guarinogabriel** [comment]
@sammcj Could you please contribute to the project by adding this feature? Since you are using Nginx and PostgreSQL, it would be great if you can add the logic to support that configuration on the project.

Please let me know.
Thanks.
Gabriel

**Comment by maycollozadelpier** [comment]
dudo mucho que o haga por motivos personales  lo siento

2016-07-05 8:50 GMT-05:00 Gabriel Guarino <notifications@github.com>:
