### ISSUE TITLE
Any ideas why installing messed up my git credential? 

### ISSUE THREAD

**Issue by yifanchen** [guarinogabriel/mac-cli#27]
My git credentials are wrong on both github and gitbucket, it keeps prompting me to enter username and password when I do `push` or `pull`. It's quite annoying.

Any ideas what's going on with it?

**Comment by guarinogabriel** [comment]
Hi there!

I am not sure if that is directly related to the script. When you said gitbucket, I think that you are referring to this: https://github.com/gitbucket/gitbucket (not Bitbucket), so the issue is 100% related to Github.

Please follow these instructions to restore the GIT credential caching:
https://help.github.com/articles/caching-your-github-password-in-git/
