### ISSUE TITLE
mac brew:list => two lists?

### ISSUE THREAD

**Issue by ChrisGitIt** [guarinogabriel/Mac-CLI#76]
Hi all,

i just installed mac-cli and when i type "mac brew:list" i see all packages twice.

I had homebrew installed long before and just recently installed "mac". 
Are all my homebrew packages installed twice? I just had a glance while installing and some packages seem to be installed into /usr/local/bin and not in /usr/local/Cellar ... somehow, there are also many symlinks from /usr/local/bin to /usr/local/Cellar.

Do i need to uninstall my old homebrew installation? Or are the doubled packages just a display problem?

Greets,

Chris

**Comment by guarinogabriel** [comment]
Hi @ChrisGitIt,

Thanks for reporting this. The brew packages are installed only once, you can check that by running:
`brew list`

The `mac brew:list` command was showing the packages twice, but it was a displaying error.
Since there is no point on running `mac brew:list` instead of `brew list`, I removed that command.

Feel free of adding more brew commands if there is anything we can automatize for Homebrew.

Thanks!
Gabriel
